language: python
python:
    # - "2.6"
    - "2.7"
    # - "3.3"
    # - "3.4"
    - "3.5"
    - "3.6"
    # - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install -r optional-packages.txt
  # - pip install pandas pytest requests
  # - pip install ordereddict cchardet argparse chardet
  # - pip install openpyxl==2.0.3
  - python setup.py install
script:
    - pytest
    - codecov
notifications:
  email:
    recipients:
      - kinverarity@hotmail.com
    on_success: change
    on_failure: change
